version: "3.0"
name: devs

services:

  local_db:
    container_name: local_db
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 20s
      timeout: 60s
      retries: 5
    ports:
      - ${POSTGRES_ACCESS_PORT}:5432
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/local_db_password
    secrets:
      - local_db_password
    volumes:
      - ${POSTGRES_DATA}:/var/opt/postgresql/data

  local_pgadmin:
    container_name: local_pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - ${PGADMIN_ACCESS_PORT}:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/local_db_password
    secrets:
      - local_db_password
    volumes:
      - ${PGADMIN_SERVERS_FILE}:/pgadmin4/servers.json

secrets:
  local_db_password:
    file: ./secrets/local_db/password.txt